"""通用骨架模板：存放跨芯片族通用的模板常量（链接脚本、项目信息）。"""

PROJECT_INFO_TEMPLATE = """# {project_name}

## 项目信息
- **芯片**: {chip_name} ({core})
- **主频**: {clock}MHz
- **Flash**: {flash}KB | SRAM: {ram}KB + CCM: {ccm}KB
- **生成工具**: stm32-forge v{tool_version}
- **生成时间**: {timestamp}

## 外设配置
{peripheral_list}

## 工程结构
```
{project_name}/
├── Core/
│   ├── Inc/
│   │   ├── main.h
│   │   ├── {it_h_file}
{peripheral_headers}
│   └── Src/
│       ├── main.c
│       ├── {it_c_file}
│       └── {system_file}
└── project_info.md
```

## 使用说明
1. 使用 STM32CubeIDE / Keil MDK / IAR 打开工程
2. 确保已安装 {family} HAL 库
3. 编译下载到 {chip_name} 开发板
"""

LINKER_LD_TEMPLATE = """/**
 ******************************************************************************
 * @file      {linker_file_name}
 * @author    Auto-generated by Agent-S MxSkeleton
 * @brief     Linker script for {chip_name} ({flash}KB Flash, {ram}KB RAM)
 ******************************************************************************
 */

/* Entry Point */
ENTRY(Reset_Handler)

/* Highest address of the user mode stack */
_estack = ORIGIN(RAM) + LENGTH(RAM);    /* end of RAM */

/* Generate a link error if heap and stack don't fit into RAM */
_Min_Heap_Size = 0x200;      /* required amount of heap  */
_Min_Stack_Size = 0x400;     /* required amount of stack */

/* Specify the memory areas */
MEMORY
{{
RAM (xrw)      : ORIGIN = 0x20000000, LENGTH = {ram}K
{ccm_section}FLASH (rx)     : ORIGIN = 0x08000000, LENGTH = {flash}K
}}

/* Define output sections */
SECTIONS
{{
  /* The startup code goes first into FLASH */
  .isr_vector :
  {{
    . = ALIGN(4);
    KEEP(*(.isr_vector)) /* Startup code */
    . = ALIGN(4);
  }} >FLASH

  /* The program code and other data goes into FLASH */
  .text :
  {{
    . = ALIGN(4);
    *(.text)           /* .text sections (code) */
    *(.text*)          /* .text* sections (code) */
    *(.glue_7)         /* glue arm to thumb code */
    *(.glue_7t)        /* glue thumb to arm code */
    *(.eh_frame)

    KEEP (*(.init))
    KEEP (*(.fini))

    . = ALIGN(4);
    _etext = .;        /* define a global symbols at end of code */
  }} >FLASH

  /* Constant data goes into FLASH */
  .rodata :
  {{
    . = ALIGN(4);
    *(.rodata)         /* .rodata sections (constants, strings, etc.) */
    *(.rodata*)        /* .rodata* sections (constants, strings, etc.) */
    . = ALIGN(4);
  }} >FLASH

  .ARM.extab   : {{ *(.ARM.extab* .gnu.linkonce.armextab.*) }} >FLASH
  .ARM : {{
    __exidx_start = .;
    *(.ARM.exidx*)
    __exidx_end = .;
  }} >FLASH

  .preinit_array     :
  {{
    PROVIDE_HIDDEN (__preinit_array_start = .);
    KEEP (*(.preinit_array*))
    PROVIDE_HIDDEN (__preinit_array_end = .);
  }} >FLASH

  .init_array :
  {{
    PROVIDE_HIDDEN (__init_array_start = .);
    KEEP (*(SORT(.init_array.*)))
    KEEP (*(.init_array*))
    PROVIDE_HIDDEN (__init_array_end = .);
  }} >FLASH

  .fini_array :
  {{
    PROVIDE_HIDDEN (__fini_array_start = .);
    KEEP (*(SORT(.fini_array.*)))
    KEEP (*(.fini_array*))
    PROVIDE_HIDDEN (__fini_array_end = .);
  }} >FLASH

  /* used by the startup to initialize data */
  _sidata = LOADADDR(.data);

  /* Initialized data sections goes into RAM, load LMA copy after code */
  .data :
  {{
    . = ALIGN(4);
    _sdata = .;        /* create a global symbol at data start */
    *(.data)           /* .data sections */
    *(.data*)          /* .data* sections */

    . = ALIGN(4);
    _edata = .;        /* define a global symbol at data end */
  }} >RAM AT> FLASH

{ccmram_sections}
  /* Uninitialized data section */
  . = ALIGN(4);
  .bss :
  {{
    _sbss = .;         /* define a global symbol at bss start */
    __bss_start__ = _sbss;
    *(.bss)
    *(.bss*)
    *(COMMON)

    . = ALIGN(4);
    _ebss = .;         /* define a global symbol at bss end */
    __bss_end__ = _ebss;
  }} >RAM

  /* User_heap_stack section, used to check that there is enough RAM left */
  ._user_heap_stack :
  {{
    . = ALIGN(8);
    PROVIDE ( end = . );
    PROVIDE ( _end = . );
    . = . + _Min_Heap_Size;
    . = . + _Min_Heap_Size;
    . = ALIGN(8);
  }} >RAM

  /* Remove information from the standard libraries */
  /DISCARD/ :
  {{
    libc.a ( * )
    libm.a ( * )
    libgcc.a ( * )
  }}

  .ARM.attributes 0 : {{ *(.ARM.attributes) }}
}}
"""
