"""STM32F1xx 系列骨架模板。"""

MAIN_H_TEMPLATE = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.h
  * @brief          : Header for main.c file.
  *                   This file contains the common defines of the application.
  ******************************************************************************
  * @attention
  * Chip: {chip_name} | Core: {core} | Clock: {clock}MHz
  * Flash: {flash}KB | SRAM: {ram}KB + CCM: {ccm}KB
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {{
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32f1xx_hal.h"

/* Exported types ------------------------------------------------------------*/

/* Exported constants --------------------------------------------------------*/

/* Exported macro ------------------------------------------------------------*/

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

{peripheral_prototypes}

#ifdef __cplusplus
}}
#endif

#endif /* __MAIN_H */
"""

MAIN_C_HEADER = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  * Generated by stm32-forge v{tool_version}
  * Chip: {chip_name} ({core}, {clock}MHz, {flash}KB Flash, {ram}KB SRAM + {ccm}KB CCM)
{clock_notes}
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
{peripheral_includes}

/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private macro -------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/
{peripheral_handles}

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
{peripheral_init_protos}

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
{peripheral_inits}

  /* 应用层初始化（三层架构：业务层 App_Business_Init 在此接线） */
  App_Init();

  /* USER CODE BEGIN 2 */

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {{
{main_loop_body}
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    /* Industrial hint: if IWDG is enabled, call HAL_IWDG_Refresh(&hiwdg) here */
  }}
  /* USER CODE END 3 */
}}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{{
  RCC_OscInitTypeDef RCC_OscInitStruct = {{0}};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {{0}};

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.HSEPredivValue = RCC_HSE_PREDIV_DIV1;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLMUL = {pll_mult};
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {{
    Error_Handler();
  }}

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, {flash_latency}) != HAL_OK)
  {{
    Error_Handler();
  }}
}}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{{
  /* USER CODE BEGIN Error_Handler_Debug */
  GPIO_InitTypeDef GPIO_InitStruct = {{0}};

  __disable_irq();

  /* Enable GPIO clock and configure error LED pin */
  __HAL_RCC_{error_led_port}_CLK_ENABLE();
  GPIO_InitStruct.Pin = {error_led_pin_macro};
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init({error_led_port}, &GPIO_InitStruct);

  while (1)
  {{
    HAL_GPIO_TogglePin({error_led_port}, {error_led_pin_macro});
    for (volatile uint32_t i = 0; i < 500000U; i++) {{ __NOP(); }}
  }}
  /* USER CODE END Error_Handler_Debug */
}}
"""

STM32F1XX_IT_C_TEMPLATE = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : stm32f1xx_it.c
  * @brief          : Interrupt Service Routines.
  ******************************************************************************
  * @attention
  * Generated by stm32-forge v{tool_version}
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "stm32f1xx_it.h"

/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private macro -------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/

/* External variables --------------------------------------------------------*/
{extern_handles}

/******************************************************************************/
/*           Cortex-M3 Processor Interruption and Exception Handlers          */
/******************************************************************************/

/**
  * @brief This function handles Non maskable interrupt.
  */
void NMI_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Hard fault interrupt.
  */
void HardFault_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Memory management fault.
  */
void MemManage_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Pre-fetch fault, memory access fault.
  */
void BusFault_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Undefined instruction or illegal state.
  */
void UsageFault_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles System service call via SWI instruction.
  */
void SVC_Handler(void)
{{
}}

/**
  * @brief This function handles Debug monitor.
  */
void DebugMon_Handler(void)
{{
}}

/**
  * @brief This function handles Pendable request for system service.
  */
void PendSV_Handler(void)
{{
}}

/**
  * @brief This function handles System tick timer.
  */
void SysTick_Handler(void)
{{
  HAL_IncTick();
}}

{peripheral_irq_handlers}
"""

STM32F1XX_IT_H_TEMPLATE = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : stm32f1xx_it.h
  * @brief          : This file contains the headers of the interrupt handlers.
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __STM32F1xx_IT_H
#define __STM32F1xx_IT_H

#ifdef __cplusplus
 extern "C" {{
#endif

void NMI_Handler(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);
void SVC_Handler(void);
void DebugMon_Handler(void);
void PendSV_Handler(void);
void SysTick_Handler(void);
{peripheral_irq_protos}

#ifdef __cplusplus
}}
#endif

#endif /* __STM32F1xx_IT_H */
"""

SYSTEM_STM32F1XX_TEMPLATE = """/**
  ******************************************************************************
  * @file           : system_stm32f1xx.c
  * @brief          : CMSIS Cortex-M3 Device Peripheral Access Layer
  *                   System Source File for STM32F1xx devices.
  ******************************************************************************
  * Generated by stm32-forge v{tool_version}
  ******************************************************************************
  */

#include "stm32f1xx.h"

#if !defined  (HSE_VALUE)
  #define HSE_VALUE    ((uint32_t){hse_value}) /* 8 MHz */
#endif

#if !defined  (HSI_VALUE)
  #define HSI_VALUE    ((uint32_t){hsi_value}) /* 8 MHz */
#endif

uint32_t SystemCoreClock = {clock_hz}U;

const uint8_t AHBPrescTable[16] = {{0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}};
const uint8_t APBPrescTable[8]  = {{0, 0, 0, 0, 1, 2, 3, 4}};

void SystemInit(void)
{{
  /* Reset the RCC clock configuration to the default reset state */
  RCC->CR |= (uint32_t)0x00000001;
  RCC->CFGR = 0x00000000;
  RCC->CR &= (uint32_t)0xFEF6FFFF;
  RCC->CR &= (uint32_t)0xFFFBFFFF;
  RCC->CFGR &= (uint32_t)0xF8FF0000;
  RCC->CIR = 0x00000000;

  SystemCoreClock = {clock_hz}U;
}}

void SystemCoreClockUpdate(void)
{{
  /* Placeholder: actual clock calculation depends on PLL config */
}}
"""

STARTUP_S_TEMPLATE = """/**
  ******************************************************************************
  * @file      startup_stm32f103xb.s
  * @author    Auto-generated by Agent-S MxSkeleton
  * @brief     STM32F103xB vector table for GCC toolchain.
  ******************************************************************************
  */

  .syntax unified
  .cpu cortex-m3
  .fpu softvfp
  .thumb

.global  g_pfnVectors
.global  Default_Handler

.word  _sidata
.word  _sdata
.word  _edata
.word  _sbss
.word  _ebss

  .section  .text.Reset_Handler
  .weak  Reset_Handler
  .type  Reset_Handler, %function
Reset_Handler:
  ldr   sp, =_estack

  movs  r1, #0
  b  LoopCopyDataInit

CopyDataInit:
  ldr  r3, =_sidata
  ldr  r3, [r3, r1]
  str  r3, [r0, r1]
  adds  r1, r1, #4

LoopCopyDataInit:
  ldr  r0, =_sdata
  ldr  r3, =_edata
  adds  r2, r0, r1
  cmp  r2, r3
  bcc  CopyDataInit
  ldr  r2, =_sbss
  b  LoopFillZerobss

FillZerobss:
  movs  r3, #0
  str  r3, [r2], #4

LoopFillZerobss:
  ldr  r3, = _ebss
  cmp  r2, r3
  bcc  FillZerobss

  bl  SystemInit
  bl  __libc_init_array
  bl  main
  bx  lr
.size  Reset_Handler, .-Reset_Handler

  .section  .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b  Infinite_Loop
  .size  Default_Handler, .-Default_Handler

  .macro  def_weak_alias  name
  .weak  \\name
  .thumb_set \\name, Default_Handler
  .endm

  .section  .isr_vector,"a",%progbits
  .type  g_pfnVectors, %object
  .size  g_pfnVectors, .-g_pfnVectors

g_pfnVectors:
  .word  _estack
  .word  Reset_Handler
  .word  NMI_Handler
  .word  HardFault_Handler
  .word  MemManage_Handler
  .word  BusFault_Handler
  .word  UsageFault_Handler
  .word  0
  .word  0
  .word  0
  .word  0
  .word  SVC_Handler
  .word  DebugMon_Handler
  .word  0
  .word  PendSV_Handler
  .word  SysTick_Handler

  /* External Interrupts */
  .word  WWDG_IRQHandler
  .word  PVD_IRQHandler
  .word  TAMPER_IRQHandler
  .word  RTC_IRQHandler
  .word  FLASH_IRQHandler
  .word  RCC_IRQHandler
  .word  EXTI0_IRQHandler
  .word  EXTI1_IRQHandler
  .word  EXTI2_IRQHandler
  .word  EXTI3_IRQHandler
  .word  EXTI4_IRQHandler
  .word  DMA1_Channel1_IRQHandler
  .word  DMA1_Channel2_IRQHandler
  .word  DMA1_Channel3_IRQHandler
  .word  DMA1_Channel4_IRQHandler
  .word  DMA1_Channel5_IRQHandler
  .word  DMA1_Channel6_IRQHandler
  .word  DMA1_Channel7_IRQHandler
  .word  ADC1_2_IRQHandler
  .word  USB_HP_CAN1_TX_IRQHandler
  .word  USB_LP_CAN1_RX0_IRQHandler
  .word  CAN1_RX1_IRQHandler
  .word  CAN1_SCE_IRQHandler
  .word  EXTI9_5_IRQHandler
  .word  TIM1_BRK_IRQHandler
  .word  TIM1_UP_IRQHandler
  .word  TIM1_TRG_COM_IRQHandler
  .word  TIM1_CC_IRQHandler
  .word  TIM2_IRQHandler
  .word  TIM3_IRQHandler
  .word  TIM4_IRQHandler
  .word  I2C1_EV_IRQHandler
  .word  I2C1_ER_IRQHandler
  .word  I2C2_EV_IRQHandler
  .word  I2C2_ER_IRQHandler
  .word  SPI1_IRQHandler
  .word  SPI2_IRQHandler
  .word  USART1_IRQHandler
  .word  USART2_IRQHandler
  .word  USART3_IRQHandler
  .word  EXTI15_10_IRQHandler
  .word  RTCAlarm_IRQHandler
  .word  USBWakeUp_IRQHandler

  def_weak_alias  NMI_Handler
  def_weak_alias  HardFault_Handler
  def_weak_alias  MemManage_Handler
  def_weak_alias  BusFault_Handler
  def_weak_alias  UsageFault_Handler
  def_weak_alias  SVC_Handler
  def_weak_alias  DebugMon_Handler
  def_weak_alias  PendSV_Handler
  def_weak_alias  SysTick_Handler
  def_weak_alias  WWDG_IRQHandler
  def_weak_alias  PVD_IRQHandler
  def_weak_alias  TAMPER_IRQHandler
  def_weak_alias  RTC_IRQHandler
  def_weak_alias  FLASH_IRQHandler
  def_weak_alias  RCC_IRQHandler
  def_weak_alias  EXTI0_IRQHandler
  def_weak_alias  EXTI1_IRQHandler
  def_weak_alias  EXTI2_IRQHandler
  def_weak_alias  EXTI3_IRQHandler
  def_weak_alias  EXTI4_IRQHandler
  def_weak_alias  DMA1_Channel1_IRQHandler
  def_weak_alias  DMA1_Channel2_IRQHandler
  def_weak_alias  DMA1_Channel3_IRQHandler
  def_weak_alias  DMA1_Channel4_IRQHandler
  def_weak_alias  DMA1_Channel5_IRQHandler
  def_weak_alias  DMA1_Channel6_IRQHandler
  def_weak_alias  DMA1_Channel7_IRQHandler
  def_weak_alias  ADC1_2_IRQHandler
  def_weak_alias  USB_HP_CAN1_TX_IRQHandler
  def_weak_alias  USB_LP_CAN1_RX0_IRQHandler
  def_weak_alias  CAN1_RX1_IRQHandler
  def_weak_alias  CAN1_SCE_IRQHandler
  def_weak_alias  EXTI9_5_IRQHandler
  def_weak_alias  TIM1_BRK_IRQHandler
  def_weak_alias  TIM1_UP_IRQHandler
  def_weak_alias  TIM1_TRG_COM_IRQHandler
  def_weak_alias  TIM1_CC_IRQHandler
  def_weak_alias  TIM2_IRQHandler
  def_weak_alias  TIM3_IRQHandler
  def_weak_alias  TIM4_IRQHandler
  def_weak_alias  I2C1_EV_IRQHandler
  def_weak_alias  I2C1_ER_IRQHandler
  def_weak_alias  I2C2_EV_IRQHandler
  def_weak_alias  I2C2_ER_IRQHandler
  def_weak_alias  SPI1_IRQHandler
  def_weak_alias  SPI2_IRQHandler
  def_weak_alias  USART1_IRQHandler
  def_weak_alias  USART2_IRQHandler
  def_weak_alias  USART3_IRQHandler
  def_weak_alias  EXTI15_10_IRQHandler
  def_weak_alias  RTCAlarm_IRQHandler
  def_weak_alias  USBWakeUp_IRQHandler
"""


# 模板包元数据（自动发现锚点）：__init__ 扫描本模块据此注册 OrgTemplates。
ORG_META = {
    "family_key": "STM32F1xx",
    "hal_header": "stm32f1xx_hal.h",
    "supported_peripherals": ("GPIO", "TIM", "UART", "SPI", "I2C", "ADC", "DMA"),
    "main_h_template": MAIN_H_TEMPLATE,
    "main_c_header": MAIN_C_HEADER,
    "it_c_template": STM32F1XX_IT_C_TEMPLATE,
    "it_h_template": STM32F1XX_IT_H_TEMPLATE,
    "system_template": SYSTEM_STM32F1XX_TEMPLATE,
    "startup_template": STARTUP_S_TEMPLATE,
}
