"""STM32G4xx 系列骨架模板。"""

MAIN_H_TEMPLATE = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.h
  * @brief          : Header for main.c file.
  *                   This file contains the common defines of the application.
  ******************************************************************************
  * @attention
  * Chip: {chip_name} | Core: {core} | Clock: {clock}MHz
  * Flash: {flash}KB | SRAM: {ram}KB + CCM: {ccm}KB
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {{
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32g4xx_hal.h"

/* Exported types ------------------------------------------------------------*/

/* Exported constants --------------------------------------------------------*/

/* Exported macro ------------------------------------------------------------*/

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

{peripheral_prototypes}

#ifdef __cplusplus
}}
#endif

#endif /* __MAIN_H */
"""

MAIN_C_HEADER = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  ******************************************************************************
  * @attention
  * Generated by stm32-forge v{tool_version}
  * Chip: {chip_name} ({core}, {clock}MHz, {flash}KB Flash, {ram}KB SRAM + {ccm}KB CCM)
{clock_notes}
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include <string.h>   /* strlen/memset（真编译验证：模板用 C 库函数须 include） */
#include <stdio.h>    /* snprintf */
{peripheral_includes}

/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private macro -------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/
{peripheral_handles}

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
{peripheral_init_protos}

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{{
  /* USER CODE BEGIN 1 */

  /* USER CODE END 1 */

  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* USER CODE BEGIN Init */

  /* USER CODE END Init */

  /* Configure the system clock */
  SystemClock_Config();

  /* USER CODE BEGIN SysInit */

  /* USER CODE END SysInit */

  /* Initialize all configured peripherals */
{peripheral_inits}

  /* 应用层初始化（三层架构：业务层 App_Business_Init 在此接线） */
  App_Init();

  /* USER CODE BEGIN 2 */

  /* USER CODE END 2 */

  /* Infinite loop */
  /* USER CODE BEGIN WHILE */
  while (1)
  {{
{main_loop_body}
    /* USER CODE END WHILE */

    /* USER CODE BEGIN 3 */
    /* Industrial hint: if IWDG is enabled, call HAL_IWDG_Refresh(&hiwdg) here */
  }}
  /* USER CODE END 3 */
}}

/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{{
  RCC_OscInitTypeDef RCC_OscInitStruct = {{0}};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {{0}};

  /** Configure the main internal regulator output voltage
  */
  __HAL_RCC_PWR_CLK_ENABLE();
  __HAL_PWR_VOLTAGESCALING_CONFIG({voltage_scale});

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
  RCC_OscInitStruct.HSEState = RCC_HSE_ON;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
  RCC_OscInitStruct.PLL.PLLM = {pll_m};
  RCC_OscInitStruct.PLL.PLLN = {pll_n};
  RCC_OscInitStruct.PLL.PLLP = {pll_p};
  RCC_OscInitStruct.PLL.PLLQ = {pll_q};
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {{
    Error_Handler();
  }}

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, {flash_latency}) != HAL_OK)
  {{
    Error_Handler();
  }}
}}

/* USER CODE BEGIN 4 */

/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{{
  /* USER CODE BEGIN Error_Handler_Debug */
  GPIO_InitTypeDef GPIO_InitStruct = {{0}};

  __disable_irq();

  /* Enable GPIO clock and configure error LED pin */
  __HAL_RCC_{error_led_port}_CLK_ENABLE();
  GPIO_InitStruct.Pin = {error_led_pin_macro};
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init({error_led_port}, &GPIO_InitStruct);

  while (1)
  {{
    HAL_GPIO_TogglePin({error_led_port}, {error_led_pin_macro});
    for (volatile uint32_t i = 0; i < 500000U; i++) {{ __NOP(); }}
  }}
  /* USER CODE END Error_Handler_Debug */
}}
"""

STM32G4XX_IT_C_TEMPLATE = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : stm32g4xx_it.c
  * @brief          : Interrupt Service Routines.
  ******************************************************************************
  * @attention
  * Generated by stm32-forge v{tool_version}
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "stm32g4xx_it.h"

/* Private typedef -----------------------------------------------------------*/

/* Private define ------------------------------------------------------------*/

/* Private macro -------------------------------------------------------------*/

/* Private variables ---------------------------------------------------------*/

/* External variables --------------------------------------------------------*/
{extern_handles}

/******************************************************************************/
/*           Cortex-M4 Processor Interruption and Exception Handlers          */
/******************************************************************************/

/**
  * @brief This function handles Non maskable interrupt.
  */
void NMI_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Hard fault interrupt.
  */
void HardFault_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Memory management fault.
  */
void MemManage_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Pre-fetch fault, memory access fault.
  */
void BusFault_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles Undefined instruction or illegal state.
  */
void UsageFault_Handler(void)
{{
  while (1)
  {{
  }}
}}

/**
  * @brief This function handles System service call via SWI instruction.
  */
void SVC_Handler(void)
{{
}}

/**
  * @brief This function handles Debug monitor.
  */
void DebugMon_Handler(void)
{{
}}

/**
  * @brief This function handles Pendable request for system service.
  */
void PendSV_Handler(void)
{{
}}

/**
  * @brief This function handles System tick timer.
  */
void SysTick_Handler(void)
{{
  HAL_IncTick();
}}

{peripheral_irq_handlers}
"""

STM32G4XX_IT_H_TEMPLATE = """/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : stm32g4xx_it.h
  * @brief          : This file contains the headers of the interrupt handlers.
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __STM32G4xx_IT_H
#define __STM32G4xx_IT_H

#ifdef __cplusplus
 extern "C" {{
#endif

void NMI_Handler(void);
void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);
void UsageFault_Handler(void);
void SVC_Handler(void);
void DebugMon_Handler(void);
void PendSV_Handler(void);
void SysTick_Handler(void);
{peripheral_irq_protos}

#ifdef __cplusplus
}}
#endif

#endif /* __STM32G4xx_IT_H */
"""

SYSTEM_STM32G4XX_TEMPLATE = """/**
  ******************************************************************************
  * @file           : system_stm32g4xx.c
  * @brief          : CMSIS Cortex-M4 Device Peripheral Access Layer
  *                   System Source File for STM32G431xx devices.
  ******************************************************************************
  * Generated by stm32-forge v{tool_version}
  ******************************************************************************
  */

#include "stm32g4xx.h"

#if !defined  (HSE_VALUE)
  #define HSE_VALUE    ((uint32_t){hse_value}) /* 8 MHz */
#endif

#if !defined  (HSI_VALUE)
  #define HSI_VALUE    ((uint32_t){hsi_value}) /* 16 MHz */
#endif

uint32_t SystemCoreClock = {clock_hz}U;

const uint8_t AHBPrescTable[16] = {{0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 6, 7, 8, 9}};
const uint8_t APBPrescTable[8]  = {{0, 0, 0, 0, 1, 2, 3, 4}};

void SystemInit(void)
{{
  /* FPU settings */
  #if (__FPU_PRESENT == 1) && (__FPU_USED == 1)
    SCB->CPACR |= ((3UL << 10*2)|(3UL << 11*2));
  #endif

  /* Reset the RCC clock configuration to the default reset state */
  RCC->CR |= (uint32_t)0x00000001;
  RCC->CFGR = 0x00000000;
  RCC->CR &= (uint32_t)0xFEF6FFFF;
  RCC->PLLCFGR = 0x24003010;
  RCC->CR &= (uint32_t)0xFFFBFFFF;
  RCC->CIR = 0x00000000;

  SystemCoreClock = {clock_hz}U;
}}

void SystemCoreClockUpdate(void)
{{
  /* Placeholder: actual clock calculation depends on PLL config */
}}
"""

STARTUP_S_TEMPLATE = """/**
  ******************************************************************************
  * @file      startup_stm32g431xx.s
  * @author    Auto-generated by Agent-S MxSkeleton
  * @brief     STM32G431xx vector table for GCC toolchain.
  ******************************************************************************
  */

  .syntax unified
  .cpu cortex-m4
  .fpu softvfp
  .thumb

.global  g_pfnVectors
.global  Default_Handler

/* start address for the initialization values of the .data section */
.word  _sidata
/* start address for the .data section */
.word  _sdata
/* end address for the .data section */
.word  _edata
/* start address for the .bss section */
.word  _sbss
/* end address for the .bss section */
.word  _ebss

/**
 * @brief  This is the code that gets called when the processor first
 *          starts execution following a reset event.
 */
  .section  .text.Reset_Handler
  .weak  Reset_Handler
  .type  Reset_Handler, %function
Reset_Handler:
  ldr   sp, =_estack     /* set stack pointer */

/* Copy the data segment initializers from flash to SRAM */
  movs  r1, #0
  b  LoopCopyDataInit

CopyDataInit:
  ldr  r3, =_sidata
  ldr  r3, [r3, r1]
  str  r3, [r0, r1]
  adds  r1, r1, #4

LoopCopyDataInit:
  ldr  r0, =_sdata
  ldr  r3, =_edata
  adds  r2, r0, r1
  cmp  r2, r3
  bcc  CopyDataInit
  ldr  r2, =_sbss
  b  LoopFillZerobss

/* Zero fill the bss segment */
FillZerobss:
  movs  r3, #0
  str  r3, [r2], #4

LoopFillZerobss:
  ldr  r3, = _ebss
  cmp  r2, r3
  bcc  FillZerobss

/* Call the clock system initialization function */
  bl  SystemInit
/* Call static constructors */
  bl  __libc_init_array
/* Call the application's entry point */
  bl  main
  bx  lr
.size  Reset_Handler, .-Reset_Handler

/**
 * @brief  This is the code that gets called when the processor receives an
 *         unexpected interrupt.
 */
  .section  .text.Default_Handler,"ax",%progbits
Default_Handler:
Infinite_Loop:
  b  Infinite_Loop
  .size  Default_Handler, .-Default_Handler

/* Macro to define weak aliases for exception handlers */
  .macro  def_weak_alias  name
  .weak  \\name
  .thumb_set \\name, Default_Handler
  .endm

/* Exception and interrupt vector table */
  .section  .isr_vector,"a",%progbits
  .type  g_pfnVectors, %object
  .size  g_pfnVectors, .-g_pfnVectors

g_pfnVectors:
  .word  _estack                         /* Top of Stack */
  .word  Reset_Handler                   /* Reset Handler */
  .word  NMI_Handler                     /* NMI Handler */
  .word  HardFault_Handler               /* Hard Fault Handler */
  .word  MemManage_Handler               /* MPU Fault Handler */
  .word  BusFault_Handler                /* Bus Fault Handler */
  .word  UsageFault_Handler              /* Usage Fault Handler */
  .word  0                               /* Reserved */
  .word  0                               /* Reserved */
  .word  0                               /* Reserved */
  .word  0                               /* Reserved */
  .word  SVC_Handler                     /* SVCall Handler */
  .word  DebugMon_Handler                /* Debug Monitor Handler */
  .word  0                               /* Reserved */
  .word  PendSV_Handler                  /* PendSV Handler */
  .word  SysTick_Handler                 /* SysTick Handler */

  /* External Interrupts */
  .word  WWDG_IRQHandler
  .word  PVD_IRQHandler
  .word  TAMP_STAMP_IRQHandler
  .word  RTC_WKUP_IRQHandler
  .word  FLASH_IRQHandler
  .word  RCC_IRQHandler
  .word  EXTI0_IRQHandler
  .word  EXTI1_IRQHandler
  .word  EXTI2_IRQHandler
  .word  EXTI3_IRQHandler
  .word  EXTI4_IRQHandler
  .word  DMA1_Stream0_IRQHandler
  .word  DMA1_Stream1_IRQHandler
  .word  DMA1_Stream2_IRQHandler
  .word  DMA1_Stream3_IRQHandler
  .word  DMA1_Stream4_IRQHandler
  .word  DMA1_Stream5_IRQHandler
  .word  DMA1_Stream6_IRQHandler
  .word  ADC_IRQHandler
  .word  CAN1_TX_IRQHandler
  .word  CAN1_RX0_IRQHandler
  .word  CAN1_RX1_IRQHandler
  .word  CAN1_SCE_IRQHandler
  .word  EXTI9_5_IRQHandler
  .word  TIM1_BRK_TIM9_IRQHandler
  .word  TIM1_UP_TIM10_IRQHandler
  .word  TIM1_TRG_COM_TIM11_IRQHandler
  .word  TIM1_CC_IRQHandler
  .word  TIM2_IRQHandler
  .word  TIM3_IRQHandler
  .word  TIM4_IRQHandler
  .word  I2C1_EV_IRQHandler
  .word  I2C1_ER_IRQHandler
  .word  I2C2_EV_IRQHandler
  .word  I2C2_ER_IRQHandler
  .word  SPI1_IRQHandler
  .word  SPI2_IRQHandler
  .word  USART1_IRQHandler
  .word  USART2_IRQHandler
  .word  USART3_IRQHandler
  .word  EXTI15_10_IRQHandler
  .word  RTC_Alarm_IRQHandler
  .word  OTG_FS_WKUP_IRQHandler
  .word  TIM8_BRK_TIM12_IRQHandler
  .word  TIM8_UP_TIM13_IRQHandler
  .word  TIM8_TRG_COM_TIM14_IRQHandler
  .word  TIM8_CC_IRQHandler
  .word  DMA1_Stream7_IRQHandler
  .word  FSMC_IRQHandler
  .word  SDIO_IRQHandler
  .word  TIM5_IRQHandler
  .word  SPI3_IRQHandler
  .word  UART4_IRQHandler
  .word  UART5_IRQHandler
  .word  TIM6_DAC_IRQHandler
  .word  TIM7_IRQHandler
  .word  DMA2_Stream0_IRQHandler
  .word  DMA2_Stream1_IRQHandler
  .word  DMA2_Stream2_IRQHandler
  .word  DMA2_Stream3_IRQHandler
  .word  DMA2_Stream4_IRQHandler
  .word  ETH_IRQHandler
  .word  ETH_WKUP_IRQHandler
  .word  CAN2_TX_IRQHandler
  .word  CAN2_RX0_IRQHandler
  .word  CAN2_RX1_IRQHandler
  .word  CAN2_SCE_IRQHandler
  .word  OTG_FS_IRQHandler
  .word  DMA2_Stream5_IRQHandler
  .word  DMA2_Stream6_IRQHandler
  .word  DMA2_Stream7_IRQHandler
  .word  USART6_IRQHandler
  .word  I2C3_EV_IRQHandler
  .word  I2C3_ER_IRQHandler
  .word  OTG_HS_EP1_OUT_IRQHandler
  .word  OTG_HS_EP1_IN_IRQHandler
  .word  OTG_HS_WKUP_IRQHandler
  .word  OTG_HS_IRQHandler
  .word  DCMI_IRQHandler
  .word  0
  .word  HASH_RNG_IRQHandler
  .word  FPU_IRQHandler

/* Provide weak aliases for all handlers */
  def_weak_alias  NMI_Handler
  def_weak_alias  HardFault_Handler
  def_weak_alias  MemManage_Handler
  def_weak_alias  BusFault_Handler
  def_weak_alias  UsageFault_Handler
  def_weak_alias  SVC_Handler
  def_weak_alias  DebugMon_Handler
  def_weak_alias  PendSV_Handler
  def_weak_alias  SysTick_Handler
  def_weak_alias  WWDG_IRQHandler
  def_weak_alias  PVD_IRQHandler
  def_weak_alias  TAMP_STAMP_IRQHandler
  def_weak_alias  RTC_WKUP_IRQHandler
  def_weak_alias  FLASH_IRQHandler
  def_weak_alias  RCC_IRQHandler
  def_weak_alias  EXTI0_IRQHandler
  def_weak_alias  EXTI1_IRQHandler
  def_weak_alias  EXTI2_IRQHandler
  def_weak_alias  EXTI3_IRQHandler
  def_weak_alias  EXTI4_IRQHandler
  def_weak_alias  DMA1_Stream0_IRQHandler
  def_weak_alias  DMA1_Stream1_IRQHandler
  def_weak_alias  DMA1_Stream2_IRQHandler
  def_weak_alias  DMA1_Stream3_IRQHandler
  def_weak_alias  DMA1_Stream4_IRQHandler
  def_weak_alias  DMA1_Stream5_IRQHandler
  def_weak_alias  DMA1_Stream6_IRQHandler
  def_weak_alias  ADC_IRQHandler
  def_weak_alias  CAN1_TX_IRQHandler
  def_weak_alias  CAN1_RX0_IRQHandler
  def_weak_alias  CAN1_RX1_IRQHandler
  def_weak_alias  CAN1_SCE_IRQHandler
  def_weak_alias  EXTI9_5_IRQHandler
  def_weak_alias  TIM1_BRK_TIM9_IRQHandler
  def_weak_alias  TIM1_UP_TIM10_IRQHandler
  def_weak_alias  TIM1_TRG_COM_TIM11_IRQHandler
  def_weak_alias  TIM1_CC_IRQHandler
  def_weak_alias  TIM2_IRQHandler
  def_weak_alias  TIM3_IRQHandler
  def_weak_alias  TIM4_IRQHandler
  def_weak_alias  I2C1_EV_IRQHandler
  def_weak_alias  I2C1_ER_IRQHandler
  def_weak_alias  I2C2_EV_IRQHandler
  def_weak_alias  I2C2_ER_IRQHandler
  def_weak_alias  SPI1_IRQHandler
  def_weak_alias  SPI2_IRQHandler
  def_weak_alias  USART1_IRQHandler
  def_weak_alias  USART2_IRQHandler
  def_weak_alias  USART3_IRQHandler
  def_weak_alias  EXTI15_10_IRQHandler
  def_weak_alias  RTC_Alarm_IRQHandler
  def_weak_alias  OTG_FS_WKUP_IRQHandler
  def_weak_alias  TIM8_BRK_TIM12_IRQHandler
  def_weak_alias  TIM8_UP_TIM13_IRQHandler
  def_weak_alias  TIM8_TRG_COM_TIM14_IRQHandler
  def_weak_alias  TIM8_CC_IRQHandler
  def_weak_alias  DMA1_Stream7_IRQHandler
  def_weak_alias  FSMC_IRQHandler
  def_weak_alias  SDIO_IRQHandler
  def_weak_alias  TIM5_IRQHandler
  def_weak_alias  SPI3_IRQHandler
  def_weak_alias  UART4_IRQHandler
  def_weak_alias  UART5_IRQHandler
  def_weak_alias  TIM6_DAC_IRQHandler
  def_weak_alias  TIM7_IRQHandler
  def_weak_alias  DMA2_Stream0_IRQHandler
  def_weak_alias  DMA2_Stream1_IRQHandler
  def_weak_alias  DMA2_Stream2_IRQHandler
  def_weak_alias  DMA2_Stream3_IRQHandler
  def_weak_alias  DMA2_Stream4_IRQHandler
  def_weak_alias  ETH_IRQHandler
  def_weak_alias  ETH_WKUP_IRQHandler
  def_weak_alias  CAN2_TX_IRQHandler
  def_weak_alias  CAN2_RX0_IRQHandler
  def_weak_alias  CAN2_RX1_IRQHandler
  def_weak_alias  CAN2_SCE_IRQHandler
  def_weak_alias  OTG_FS_IRQHandler
  def_weak_alias  DMA2_Stream5_IRQHandler
  def_weak_alias  DMA2_Stream6_IRQHandler
  def_weak_alias  DMA2_Stream7_IRQHandler
  def_weak_alias  USART6_IRQHandler
  def_weak_alias  I2C3_EV_IRQHandler
  def_weak_alias  I2C3_ER_IRQHandler
  def_weak_alias  OTG_HS_EP1_OUT_IRQHandler
  def_weak_alias  OTG_HS_EP1_IN_IRQHandler
  def_weak_alias  OTG_HS_WKUP_IRQHandler
  def_weak_alias  OTG_HS_IRQHandler
  def_weak_alias  DCMI_IRQHandler
  def_weak_alias  HASH_RNG_IRQHandler
  def_weak_alias  FPU_IRQHandler
"""


# 模板包元数据（自动发现锚点）：__init__ 扫描本模块据此注册 OrgTemplates。
ORG_META = {
    "family_key": "STM32G4xx",
    "hal_header": "stm32g4xx_hal.h",
    "supported_peripherals": ("GPIO", "TIM", "UART", "SPI", "I2C", "ADC", "DAC", "DMA",
                              "OPAMP", "COMP", "FDCAN", "RTC", "IWDG", "WWDG", "CRC", "RNG"),
    "main_h_template": MAIN_H_TEMPLATE,
    "main_c_header": MAIN_C_HEADER,
    "it_c_template": STM32G4XX_IT_C_TEMPLATE,
    "it_h_template": STM32G4XX_IT_H_TEMPLATE,
    "system_template": SYSTEM_STM32G4XX_TEMPLATE,
    "startup_template": STARTUP_S_TEMPLATE,
}
